### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Wellington Silva
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
#localhost
# baseurl: ""
# gh-pages
url: "https://sswellington.github.io" 
baseurl: "/sobre"

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Wellington Silva
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Bem-vindo
# email: Your E-Mail address for the email button.
email: wellingtons@id.uff.br
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: sswellington
# codepen_username: exampleUser
# dev_username: exampleUser
linkedin_username: sswellington
twitter_username: __wellws__
instagram_username: __wellws__
blogger_username: blog

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Sobre
# about_me_description: This will be displayed under the title.
about_me_description: Pós-graduando em Arquitetura e Infraestrutura de Tecnologia da Informação pela Faculdade Futura do Grupo Educacional Faveni. Licenciado em Ciência da Computação, graduado pela Universidade Federal Fluminense (UFF). Aprovado no processo seletivo para ingresso no Instituto Federal de Educação, Ciência e Tecnologia Fluminense (IFF campus Campos-Centro) no ano de 2013. Participou do projeto de Iniciação Científica. Obteve artigo premiado como Finalist Paper in TCCLS Best Paper Award - Presented at the 2019 IEEE International Symposium on Computer-based Medical Systems (CBMS), IEEE Technical Commitee on Computational Life Sciences. Membro da Sociedade Brasileira de Computação desde de 2018. Membro do Grupo de Pesquisa ANOTi/INFES/UFF. Interesse na área de Processamento Digital de Imagens e Aprendizagem de Máquina.

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Educação & Experiência
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: http://lattes.cnpq.br/9272070981915554

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projetos
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
# os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contato
# contact_description: This will be displayed under the title.
contact_description: Olá, espero por seu contato.
# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: sswellington/sswellington.github.io/sobre
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-161159158-1"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
